### ISSUE TITLE
How to build the command line version of Diffany?

### ISSUE THREAD

**Issue by xflicsu** [thpar/diffany#259]
Hello, I wonder use Diffany to identify different networks with command line.
How to build the command line version of Diffany?

**Comment by thpar** [comment]
Requirements: [JDK][], [git][] and [maven][]

[JDK]: http://www.oracle.com/technetwork/java/javase/downloads/index.html
[git]: https://git-scm.com/downloads
[maven]: http://maven.apache.org/

You'll need to clone the source code with git (or download the zip-file and unzip it)
```
$ git clone https://github.com/thpar/diffany.git
```
Then let maven build the project:
```
$ cd diffany/diffany
$ mvn clean install
```

This will generate a `target` folder, containing two .jar files. `diffany-version.jar` is the Cytoscape App. `diffany-version-with-dependencies.jar` can be run on the commandline.

See the [manual][] in this repo for commandline options.

[manual]: https://github.com/thpar/diffany/blob/master/manual-commandline.md
